# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0362e8e2ce4226bd6a5cc12dc63eaeb22b10adf3e26e73741c1f4d61268516bbe1dc5213a7950cf7479b83f918d1501eb3101794abd0a6dd34a2ee463f1bfbb2

test:
  secret_key_base: 7ebf190e4a308381488085cab17b38314708abf10caa790ff78befec4cfa1eb54adf78f812e47a136e5f644170e93f457bc148809b8266ea90414c36bc831ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
